version: '3.9'

services:
  ngx:
    image: mynginx:v1
    volumes:
      - ./nginx-data:/var/www/html
      - ./nginx-log:/var/log/nginx
      - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-conf/:/etc/nginx/conf.d/

    ports:
      - "80:80"
      - "8080:8080"

