version: '3.9'

services:
  ngx:
    image: mynginx:v1
    volumes:
      - ./ngx-data:/var/www/html
      - ./ngx-log:/var/log/nginx
      - ./ngx-conf/nginx.conf:/etc/nginx/nginx.conf
      - ./ngx-conf/:/etc/nginx/conf.d/

    ports:
      - "80:80"
      - "8080:8080"

